apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: &app cloudflare-tunnel-ingress-controller
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "10"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    chart: *app
    repoURL: strrl.dev/cloudflare-tunnel-ingress-controller
    targetRevision: 0.0.18
    helm:
      releaseName: *app
      valuesObject:
        cloudflare:
          secretRef:
            name: cloudflare-secrets
            accountIDKey: account_id
            tunnelNameKey: tunnel_name
            apiTokenKey: api_token
  destination:
    name: in-cluster
    namespace: *app
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
