apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: &app external-dns
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "10"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    chart: *app
    repoURL: https://kubernetes-sigs.github.io/external-dns/
    targetRevision: 1.16.1
    helm:
      releaseName: *app
      valuesObject:
        provider:
          name: cloudflare
        env:
          - name: CF_API_TOKEN
            valueFrom:
              secretKeyRef:
                name: external-dns-secrets
                key: cloudflare-api-token
  destination:
    name: in-cluster
    namespace: *app
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
