apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets-objects
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "15"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/initrd/argocd.git
    path: apps/infra/objects/external-secrets
  destination:
    name: in-cluster
    namespace: external-secrets
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
