apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: &app openebs
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "10"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    chart: *app
    repoURL: https://openebs.github.io/openebs
    targetRevision: 4.2.x
    helm:
      releaseName: *app
      valuesObject:
        engines:
          local:
            zfs:
              enabled: false
          replicated:
            mayastor:
              enabled: false
        zfs-localpv:
          crds:
            zfs-localpv:
              enabled: false
            csi:
              volumeSnapshots:
                enabled: false
        lvm-localpv:
          lvmNode:
            kubeletDir: "/var/lib/k0s/kubelet/"
  destination:
    name: in-cluster
    namespace: *app
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
