apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: &app vault-secrets-operator
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "10"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    chart: *app
    repoURL: https://helm.releases.hashicorp.com
    targetRevision: 0.10.x
    helm:
      releaseName: *app
      valuesObject:
        defaultVaultConnection:
          enabled: true
          name: default-vault-connection
          address: "http://vault.vault.svc.cluster.local:8200"
          skipTLSVerify: false
        defaultAuthMethod:
          enabled: true
          method: kubernetes
          mount: kubernetes
          kubernetes:
            role: default-app-role
  destination:
    name: in-cluster
    namespace: vault-secrets-operator-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
