apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: external-dns-secrets
  namespace: external-dns
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  data:
  - secretKey: cloudflare-api-token
    remoteRef:
      key: external-dns/cloudflare-api-token
      property: token
