apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: &app external-dns
resources:
  - namespace.yaml
  - externalsecret-external-dns-secrets.yaml
helmCharts:
  - name: *app
    repo: https://kubernetes-sigs.github.io/external-dns/
    version: 1.16.1
    releaseName: *app
    namespace: *app
    valuesInline:
      provider:
        name: cloudflare
      env:
        - name: CF_API_TOKEN
          valueFrom:
            secretKeyRef:
              name: external-dns-secrets
              key: cloudflare-api-token
